import fs from "node:fs";
import path from "node:path";

import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';
// @ts-ignore
import {SidebarConfig} from "@docusaurus/plugin-content-docs/src/sidebars/types";
import apisidebar from "./docs/api/sidebar";

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebarJsonPath = path.resolve(__dirname, './sidebar-adr-architecture.json');
const sidebarJsonUserguidePath = path.resolve(__dirname, './sidebar-userguide.json');
const sidebarJsonSRSPath = path.resolve(__dirname, './sidebar-srs.json');

const parseSidebar = (filePath: string): SidebarConfig => {
  if (!fs.existsSync(filePath)) {
    return [];
  }
  try {
    const data = JSON.parse(fs.readFileSync(filePath, 'utf-8'));
    return data ?? [];
  } catch (e) {
    return [];
  }
};

const tutorialSidebar: SidebarConfig = parseSidebar(sidebarJsonPath);
const sidebarUserguide: SidebarConfig = parseSidebar(sidebarJsonUserguidePath);
const sidebarSRS: SidebarConfig = parseSidebar(sidebarJsonSRSPath);

const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  //tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  tutorialSidebar: tutorialSidebar,
  sidebarApi: apisidebar,
  sidebarUserguide: sidebarUserguide,
  sidebarSRS: sidebarSRS,
};

export default sidebars;
