import fs from "node:fs";
import path from "node:path";

import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';
// @ts-ignore
import {SidebarConfig} from "@docusaurus/plugin-content-docs/src/sidebars/types";

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebarJsonPath = path.resolve(__dirname, './sidebar.json');
const tutorialSidebar : SidebarConfig = JSON.parse(fs.readFileSync(sidebarJsonPath, 'utf-8'));

const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  //tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  tutorialSidebar: tutorialSidebar
};

export default sidebars;
