name: Test deployment

on:
  pull_request:
    branches:
      - main

jobs:
  test-deploy:
    name: Test deployment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: test1
        run: npm install css-select@latest @docusaurus/plugin-content-blog@latest

      - name: test2
        run: npm update @docusaurus/core @docusaurus/preset-classic

      - name: Test build website
        run: npm run build
